on: [ pull_request ]

jobs:
  find_changed_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find changed lines
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1
      - name: Save changed lines to file
        run: echo '${{ steps.changed_lines.outputs.changed_lines }}' > changed_lines.txt
      - name: Run Python script to convert lines
        run: python convert_lines.py